version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      - user-service
      - habit-service
      - reminder-service
      - statistics-service
      - notification-service

  user-service:
    build: ./user-service
    ports:
      - "5006:5006"

  habit-service:
    build: ./habit-service
    ports:
      - "5007:5007"

  reminder-service:
    build: ./reminder-service
    ports:
      - "5008:5008"

  statistics-service:
    build: ./statistics-service
    ports:
      - "5009:5009"

  notification-service:
    build: ./notification-service
    ports:
      - "5010:5010"

  web-client:
    build: ./web-client
    ports:
      - "3001:3001"
